modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
logoFile="logo.png"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="Inspiration for this mod comes from Wes Cook's Nutrition mod which was inspired by TerraFirmaCraft and Spice of Life. Thanks also goes to the NeoForge team and to the many mod authors who came before. Without their open source code, this would not have been possible."
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
